### ISSUE TITLE
The Lexer does not support underscores in variable names

### ISSUE THREAD

**Issue by kurtgronbech** [kbsletten/SharpStache#5]
Locally I had to add support for underscores in ScanWord with: 

if (!(template[index] == '.' || template[index] == '_' || char.IsLetter(template[index])))

**Comment by kurtgronbech** [comment]
I notice now that that change leads to other unintended consequences.

**Comment by kbsletten** [comment]
Thanks, @kurtgronbech . I'm interested in looking into this, can you give me a small example of some code that exhibits the buggy behavior? I see the template there, but can you show me what data you would like to be able to pass into this and the expected output?

Just so you know, I'm aiming to support the mustache 1.1.2 spec, so I'll have to make sure that the proposed change doesn't create more test failures than I have.

**Comment by kbsletten** [comment]
Hello @kurtgronbech ,

Wanted to let you know that I've added underscore support to v1.1 feel free to upgrade to that NuGet package if it suits your needs.
